### ISSUE TITLE
Material tab (on 1.5 snapshot)

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#258]
Hi guys,
when I disable a MaterialTabItem (es. the second one)  from a MaterialTab, it doesn't look very nice. On the previous version it was different (and better looking)
Can you fix it?

Thanks

![tabs](https://cloud.githubusercontent.com/assets/13817916/13014526/9772d706-d1b4-11e5-99b9-2dea2c3eb66d.png)

**Comment by kevzlou7979** [comment]
@MarcoCucchi Ok let me fixed this

**Comment by MarcoCucchi** [comment]
thank you Mark!

**Comment by kevzlou7979** [comment]
Ok I found what causes the problem : https://github.com/GwtMaterialDesign/gwt-material/blob/d25674d1952a5d488c0c0bf91b0c4a6861b8c89e/gwt-material/src/main/java/gwt/material/design/client/base/mixin/EnabledMixin.java

On this commit it adds a .grey class whenever it's disabled. I will commit now the fix

**Comment by MarcoCucchi** [comment]
@kevzlou7979 Great!

**Comment by kevzlou7979** [comment]
![image](https://cloud.githubusercontent.com/assets/3138071/13016843/249f1576-d1fc-11e5-966e-718719684bd0.png)
This will fixed now your issue : https://github.com/GwtMaterialDesign/gwt-material/commit/404e8afbba817490ef2dfbbd387ed0b4db6d47b5

**Comment by MarcoCucchi** [comment]
@kevzlou7979 Awesome!

**Comment by MarcoCucchi** [comment]
Hi Mark, I guess you forgot a debug Message Toast somewhere in the MaterialTabItem, when I enable/disable a tab a toast comes out with the message "Enabled", can you check it please?

Thanks.

**Comment by kevzlou7979** [comment]
Ok solved now the issue
