### ISSUE TITLE
MaterialListBox throws exception on change in selected item

### ISSUE THREAD

**Issue by volgin** [GwtMaterialDesign/gwt-material#437]
When I change a selection in a MaterialListBox, the console shows this:

> onChangeInternal threw an exception
> ConsoleLogger.java:55 Exception: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
> ConsoleLogger.java:32 undefined
> 

"onValueChange" is never executed.

I define MaterialListBox in UiBinder:

`<m:MaterialListBox ui:field="company" placeholder="Company" /> `

and then add ValueChangeHandler:

```
company.addValueChangeHandler(new ValueChangeHandler<String>() {

	@Override
	public void onValueChange(ValueChangeEvent<String> event) {
		GWT.log("Changed selection");  // never fires
	}
			
});

```

I use the Master branch.

**Comment by BenDol** [comment]
How are you adding items to the list box?

**Comment by volgin** [comment]
From an Enum:

`list.addItem(company.displayName(), company.name());`

**Comment by BenDol** [comment]
This issue seems to have been resolved after I reworked it in 2.0. I can prepare a fix for 1.6.1 release perhaps since it is an essential feature for List Boxes. I will try reproduce the issue on the master branch and apply a fix for it later tonight. Thanks for the report.

**Comment by volgin** [comment]
I switched to using add(Option). The code works but it still throws an exception:

<img width="922" alt="screen shot 2016-08-29 at 12 46 38 am" src="https://cloud.githubusercontent.com/assets/297748/18041026/37323138-6d82-11e6-83db-881ffed760fd.png">

**Comment by BenDol** [comment]
The issue is fixed here https://github.com/GwtMaterialDesign/gwt-material/commit/bd6c880576203f91e64e3d5e59872dfe6e806cb8

We will aim to release this as 1.6.1 tonight. Thanks for the report!

**Comment by kevzlou7979** [comment]
Ok will prepare now a release tonight

**Comment by volgin** [comment]
I updated to the latest code, and now the ListBox does not work at all. Every attempt to change value throws an exception:

<img width="1204" alt="screen shot 2016-09-08 at 4 51 07 am" src="https://cloud.githubusercontent.com/assets/297748/18343188/5004e7fe-7580-11e6-9196-71ef33fa3531.png">
