### ISSUE TITLE
Roboto-xxx,eot Not found when run SuperDevMode in eclipse

### ISSUE THREAD

**Issue by peggieHou** [GwtMaterialDesign/gwt-material#504]
Using GWT 2.8 and GMD 2.0-rc1
Running SuperDevMode in eclipse will show errors below on the console.
```
GET /GmdSample/font/roboto/Roboto-Thin.eot
   Sent error page: not found: C:\Users\yphou\AppData\Local\Temp\7\gwt-codeserver-5451849325673221385.tmp\com.tsmc.gmd.ui.GmdSample\compile-2\war\GmdSample\font\roboto\Roboto-Thin.eot.gz
GET /GmdSample/font/roboto/Roboto-Medium.eot
   Sent error page: not found: C:\Users\yphou\AppData\Local\Temp\7\gwt-codeserver-5451849325673221385.tmp\com.tsmc.gmd.ui.GmdSample\compile-2\war\GmdSample\font\roboto\Roboto-Medium.eot.gz
GET /GmdSample/font/roboto/Roboto-Regular.eot
   GET /GmdSample/font/roboto/Roboto-Light.eot
   Sent error page: not found: C:\Users\yphou\AppData\Local\Temp\7\gwt-codeserver-5451849325673221385.tmp\com.tsmc.gmd.ui.GmdSample\compile-2\war\GmdSample\font\roboto\Roboto-Light.eot.gz
GET /GmdSample/font/roboto/Roboto-Bold.eot
   Sent error page: not found: C:\Users\yphou\AppData\Local\Temp\7\gwt-codeserver-5451849325673221385.tmp\com.tsmc.gmd.ui.GmdSample\compile-2\war\GmdSample\font\roboto\Roboto-Bold.eot.gz
Sent error page: not found: C:\Users\yphou\AppData\Local\Temp\7\gwt-codeserver-5451849325673221385.tmp\com.tsmc.gmd.ui.GmdSample\compile-2\war\GmdSample\font\roboto\Roboto-Regular.eot.gz

```

**Comment by kevzlou7979** [comment]
This was solved in GMD Themes RC2 https://github.com/GwtMaterialDesign/gwt-material-themes/pull/11/commits/c788cbb41ae837613165908991ba9c72ec946694

**Comment by kevzlou7979** [comment]
Try out the demo showcase RC2 http://gwtmaterialdesign.github.io/gwt-material-demo/ and inspect element then view the console (Everything is fixed now)

**Comment by peggieHou** [comment]
It still happened even when I upgrade to 2.0-rc2. I checked demo case but cannot figure out what I missing.

**Comment by kevzlou7979** [comment]
Can you give me your app.xml so that I can figure out what module you are importing

**Comment by peggieHou** [comment]
Sure.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Google Inc.//DTD Google Web Toolkit 2.7.0//EN"
        "http://google-web-toolkit.googlecode.com/svn/tags/2.7.0/distro-source/core/src/gwt-module.dtd">
<module rename-to='GmdSample'>
	<!-- Inherit the core Web Toolkit stuff. -->
	<inherits name='com.google.gwt.user.User' />
	<inherits name='com.google.gwt.inject.Inject' />
	<inherits name='com.google.gwt.resources.Resources' />
	<inherits name="com.google.gwt.logging.Logging" />

	<!-- Inherit the default GWT style sheet. You can change -->
	<!-- the theme of your GWT application by uncommenting -->
	<!-- any one of the following lines. -->
	<inherits name='com.google.gwt.user.theme.standard.Standard' />

	<!-- Other module inherits -->
	<inherits name='com.gwtplatform.mvp.Mvp' />
	<inherits name='com.gwtplatform.dispatch.Dispatch' />
	<!-- <inherits name='com.gwtplatform.dispatch.rpc.DispatchRpc' /> -->
	<inherits name="com.gwtplatform.dispatch.rest.DispatchRest" /> 
	<inherits name="com.google.gwt.i18n.I18N" />
	<!-- GWT Material -->
	<inherits name="gwt.material.design.GwtMaterialWithJQueryDebug" />
	<inherits name="gwt.material.design.addins.GwtMaterialAddins" />
	<inherits name="gwt.material.design.GwtMaterialDesignBasic" />

	<!-- Specify the app entry point class. -->
	<entry-point class='com.tsmc.gmd.ui.client.GmdSampleEntryPointDispatcher' />
	<extend-configuration-property name="gin.ginjector.modules"
		value="com.tsmc.gmd.ui.client.gin.ClientModule" />
	<set-configuration-property name="gwtp.bootstrapper"
		value="com.tsmc.gmd.ui.client.GmdSampleBootstrapper" />

	<set-configuration-property name="verifyNewerVersion"
		value="false" />

	<!-- Specify the paths for translatable code -->
	<source path='client' />
	<source path='shared' />

	<!-- allow Super Dev Mode -->
	<add-linker name="xsiframe" /> 

</module>
```

**Comment by kevzlou7979** [comment]
Why you have two imports of GMD?
``` xml
<inherits name="gwt.material.design.GwtMaterialWithJQueryDebug" />
<inherits name="gwt.material.design.GwtMaterialDesignBasic" />
```

**Comment by peggieHou** [comment]
It still happened even when I remove this import.
`<inherits name="gwt.material.design.GwtMaterialDesignBasic" />`
